repos:
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      exclude: &fixtures tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
      args:
        - --in-place
        - --ignore-init-module-imports
        - --remove-all-unused-imports
        - --expand-star-imports
        - --remove-duplicate-keys
        - --remove-unused-variables
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.8