version: '3.9'

services:
  fnano:
    container_name: fnano
    restart: unless-stopped
    env_file:
      - prod.env
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:80'
    volumes:
        - .:/code
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - prod.env

volumes:
  postgres_data: