FROM python:3.10.0b4
ENV PYTHONWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
ARG HOST=0.0.0.0
ARG PORT=6969
ARG API_USERNAME=ubuntu
ARG API_PASSWORD=debian
ARG API_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
ARG API_ALGORITHM=HS256
ARG API_ACCESS_TOKEN_EXPIRE_MINUTES=5256000000
ARG DATABASE_URL=sqlite:///database.db
WORKDIR /code
COPY ./requirements-dev.txt /code/requirements-dev.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements-dev.txt
COPY . /code/