version: "3.9"
services:
  fnano:
    container_name: fnano
    restart: unless-stopped
    env_file:
      - dev.env
    build:
      context: ./
      dockerfile: Dockerfile.dev
      labels:
        - fnano
    volumes:
        - .:/code
    command:
      - /bin/sh
      - -c
      - |
        gunicorn app.main:app --workers 1 \
        --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:6969
    ports:
      - 80:6969