version: '3.9'

services:
  fnano:
    container_name: fnano
    restart: unless-stopped
    env_file:
      - staging.env
    build:
      context: ./
      dockerfile: Dockerfile.staging
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:8000'
    volumes:
        - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - staging.env

volumes:
  postgres_data: