name: autoblack_pull_request
on: workflow_dispatch

jobs:
  auto-formatter:
    name: Auto-format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
      - run: pip install black autopep8 autoflake
      - run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          printenv | grep GITHUB
          git config --global user.name 'pandalearnstocode'
          git config --global user.email 'pandalearnstocode@users.noreply.github.com'          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git remote -v
          git branch
          git status
          black .
          autopep8 --exit-code --recursive --in-place --aggressive --aggressive .
          autoflake --in-place -r --ignore-init-module-imports --remove-unused-variables --remove-all-unused-imports .
          git status
          echo ready to commit
          git commit -am "style: Format Python code with psf/black pull_request"
          echo ready to push
          git push origin ${{ github.head_ref }}
