name: "Development deploy"
on:
  pull_request:
    types: [ closed ]
jobs:
  deployment:
    name: Deploy backend app in AZ VM
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    environment: 
      name: dev
      url: 'http://dev.myrandomapp.online'
    steps:
      - name: Deploy
        run: echo I am deploying Backend! 
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: First ensure that the build is down
        run: sudo docker-compose -f docker-compose.dev.yml down
      - name: Run the build
        run: sudo docker-compose -f docker-compose.dev.yml build
      - name: Start docker compose
        run: sudo docker-compose -f docker-compose.dev.yml up --remove-orphan -d
