name: PR Validation
env:
  IMAGE_NAME: api-template-ms
  PYTHON_VERSION: '3.8'
on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  qaqc-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: (step 1) Install system level libraries.
        run: |
          sudo apt-get update
          sudo apt-get -y install libpq-dev gcc
      - name: (step 2) Checkout code from remote origin.
        uses: actions/checkout@v2
      - name: (step 3) Setup python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: (step 4) Create cache depending on requirements file.
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.pythonLocation }}-pip-
      - name: (step 5) Install dependencies & download data.
        if: steps.cache.outputs.cache-hit != 'false' # Need to change later
        run: |
          pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
          pip install PyJWT
          git fetch --depth 1 origin develop
      - name: (step 6) Run pytest & generate test coverage report (unit tests).
        run: |
          coverage run -m pytest
          coverage xml
      - name: (step 7) Check linting using pylint & generate report.
        run: |
          pip install pylint
          pylint app -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylint.log
      - name: (step 8) Check linting using flake8 and generate report
        run: |
          flake8 --exit-zero --output-file=flake8.txt .
      - name: (step 8) Run bandit and generate report for security related issue
        run: |
          bandit --exit-zero --format json --output bandit-report.json --recursive .
      - name: (step 9) Checking any secret is present in code base using gitleaks
        uses: zricethezav/gitleaks-action@master
      - name: Run Snyk to check for vulnerabilities - Monitor
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
           command: monitor
           args: --debug --org=${{ secrets.SNYK_ORGID }} --project-name=${{github.repository}} --file=/github/workspace/requirements.txt --skip-unresolved=true
      - name: Run Snyk to check for vulnerabilities - Test
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
           command: test
           args: --debug --org=${{ secrets.SNYK_ORGID }} --project-name=${{github.repository}} --file=/github/workspace/requirements.txt --json-file-output=snyk.json --skip-unresolved=true
      - name: (step 9) Upload test coverage report generated for unit tests using pytest to GitHub packages.
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml
      - name: (step 10) Upload linting errors to to GitHub packages.
        uses: actions/upload-artifact@v2
        with:
          name: linting-reports
          path: pylint.log
      - name: (step 11) Upload flake8 errors to to GitHub packages.
        uses: actions/upload-artifact@v2
        with:
          name: flake8-reports
          path: flake8.txt
      - name: (step 12) Upload bandit errors to to GitHub packages.
        uses: actions/upload-artifact@v2
        with:
          name: bandit-reports
          path: bandit-report.json
      - name: (step 12) Upload snyk errors to to GitHub packages.
        uses: actions/upload-artifact@v2
        with:
          name: snyk-reports
          path: snyk.json
      - name: (step 13) Upload app code as artifact in GitHub packages.
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !.github
            !.vscode
            !node_modules/
            !venv/
            !.mypy_cache
            !.pytest_cache
      - name: Generating the snyk report
        run: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            export PATH=~/.npm-global/bin:$PATH
            source ~/.profile
            npm install snyk-to-html -g
            snyk-to-html -i snyk.json -o Snyk.html
      - name: 'Upload Snyk report'
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report-html
          path: snyk.html
          retention-days: 5
  qaqc-publish:
    name: SonarCloud
    runs-on: ubuntu-latest
    if: always()
    needs: [qaqc-checks]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get coverage report (pytest)
        uses: actions/download-artifact@v1
        with:
          name: coverage
        continue-on-error: true
      - name: Get coverage report (pylint)
        uses: actions/download-artifact@v1
        with:
          name: linting-reports
        continue-on-error: true
      - name: Get coverage report (flake8)
        uses: actions/download-artifact@v1
        with:
          name: flake8-reports
        continue-on-error: true
      - name: Get coverage report (bandit)
        uses: actions/download-artifact@v1
        with:
          name: bandit-reports
        continue-on-error: true   
      - name: Get coverage report (snyk)
        uses: actions/download-artifact@v1
        with:
          name: snyk-reports
        continue-on-error: true
      - name: Get coverage report (snyk html)
        uses: actions/download-artifact@v1
        with:
          name: snyk-reports-html
        continue-on-error: true
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=pandalearnstocode
            -Dsonar.projectKey=api-template-ms
            -Dsonar.sources=app
            -Dsonar.dynamicAnalysis=reuseReports
            -Dsonar.python.coverage.reportPaths=coverage/coverage.xml
            -Dsonar.python.pylint.reportPaths=linting-reports/pylint.log
            -Dsonar.python.bandit.reportPaths=bandit-reports/bandit-report.json
            -Dsonar.python.flake8.reportPaths=flake8-reports/flake8.txt
            -Dsonar.python.version=3.8
            -Dsonar.exclusions=**/venv/**
            -Dsonar.sourceEncoding=UTF-8
  docker-build:
    runs-on: ubuntu-latest
    if: always()
    needs: [qaqc-publish]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get docker image version
        id: getversion
        run:  |
          MAJOR=$(cat VERSION | cut -d . -f 1)
          MINOR=$(cat VERSION | cut -d . -f 2)
          PATCH=$(cat VERSION | cut -d . -f 3)
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "::set-output name=version::${VERSION}"
      - name: 'Build image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.getversion.outputs.version }}
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
      - name: Run Snyk to check Docker images for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
          args: --file=Dockerfile
          command: monitor
  docker-push:
    runs-on: ubuntu-latest
    if: always()
    needs: [docker-build]
    steps:
      - name: Get docker image version
        id: getversion
        run:  |
          MAJOR=$(cat VERSION | cut -d . -f 1)
          MINOR=$(cat VERSION | cut -d . -f 2)
          PATCH=$(cat VERSION | cut -d . -f 3)
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "::set-output name=version::${VERSION}"
      - name: 'Push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.getversion.outputs.version }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
